version: '3.8'

services:
  frontend:
    image: nt114-frontend:latest
    ports:
      - "3000:3000" # Ánh xạ cổng 3000 của container ra cổng 3000 của host
    networks:
      - app-network

# Định nghĩa network
networks:
  app-network:
    external:
      name: thuantv
