version: '3.8'

services:
  frontend:
    build:
      context: .
    image: nt114-microservice-fe:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

# Định nghĩa network
networks:
  app-network:
    driver: bridge