# Stage 1: Build
FROM node:18-alpine AS builder
WORKDIR /app

# Khai báo build args
ARG REACT_APP_USER_SERVICE_URL
ARG REACT_APP_BOARD_SERVICE_URL
ARG REACT_APP_COLUMN_SERVICE_URL
ARG REACT_APP_CARD_SERVICE_URL
ARG REACT_APP_INVITATION_SERVICE_URL

# Set thành env để React đọc được lúc build
ENV REACT_APP_USER_SERVICE_URL=$REACT_APP_USER_SERVICE_URL
ENV REACT_APP_BOARD_SERVICE_URL=$REACT_APP_BOARD_SERVICE_URL
ENV REACT_APP_COLUMN_SERVICE_URL=$REACT_APP_COLUMN_SERVICE_URL
ENV REACT_APP_CARD_SERVICE_URL=$REACT_APP_CARD_SERVICE_URL
ENV REACT_APP_INVITATION_SERVICE_URL=$REACT_APP_INVITATION_SERVICE_URL

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve static
FROM node:18-alpine
RUN npm install -g serve
WORKDIR /app
COPY --from=builder /app/build ./build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]