server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name _;
    ssl_certificate     /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/private.key;
    resolver 127.0.0.11 valid=30s;
    resolver_timeout 5s;

    location ~ ^/auth/google(/.*)?$ {
        set $upstream "nt114-user-service";
        proxy_pass http://$upstream:3001/auth/google$1$is_args$args;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ ^/auth/github(/.*)?$ {
        set $upstream "nt114-user-service";
        proxy_pass http://$upstream:3001/auth/github$1$is_args$args;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ ^/api/users(/.*)?$ {
        set $upstream "nt114-user-service";
        proxy_pass http://$upstream:3001/api/users$1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location ~ ^/api/boards(/.*)?$ {
        set $upstream "nt114-board-service";
        proxy_pass http://$upstream:3002/api/boards$1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location ~ ^/api/columns(/.*)?$ {
        set $upstream "nt114-column-service";
        proxy_pass http://$upstream:3003/api/columns$1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location ~ ^/api/cards(/.*)?$ {
        set $upstream "nt114-card-service";
        proxy_pass http://$upstream:3004/api/cards$1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location ~ ^/api/invitations(/.*)?$ {
        set $upstream "nt114-invitation-service";
        proxy_pass http://$upstream:3005/api/invitations$1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        set $frontend "nt114-microservices-fe-frontend-1";
        proxy_pass http://$frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}