name: MicroService CD - Frontend

on:
  push:
    branches: [production]

jobs:
  deploy:
    name: Frontend - Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            set -e
            docker network create microservice-network 2>/dev/null || true
            mkdir -p /home/thuantv/project/envs

            cat > /home/thuantv/project/envs/fe.env << 'EOF'
            ${{ secrets.ENV_FRONTEND }}
            EOF

            docker pull thuan410/nt114-microservice-fe:latest
            docker stop nt114-microservice-fe || true
            docker rm nt114-microservice-fe || true
            docker run -d \
              --name nt114-microservice-fe \
              --restart unless-stopped \
              --network microservice-network \
              -p 80:80 \
              --env-file /home/thuantv/project/envs/fe.env \
              thuan410/nt114-microservice-fe:latest
            echo "✅ Frontend deployed!"
