name: MicroService CI - Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changes.yml

  build-and-push:
    name: Frontend - Build & Push
    needs: detect-changes
    if: ${{ github.event_name == 'push' && needs.detect-changes.outputs.has_changes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        run: |
          docker build -t thuan410/nt114-microservice-fe:latest \
                       -t thuan410/nt114-microservice-fe:${{ github.sha }} \
                       .
          docker push thuan410/nt114-microservice-fe:latest
          docker push thuan410/nt114-microservice-fe:${{ github.sha }}
