name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      fail-fast: false

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build -- --verbose
        env:
          NODE_ENV: production
        continue-on-error: false

      # - name: Run Tests
      #   run: npm test -- --verbose
      #   env:
      #     NODE_ENV: test
      #   continue-on-error: false

      - name: Display Build Error Details
        if: failure()
        run: |
          echo "Checking error log files..."
          find . -type f -name "*.log" -exec cat {} \; || echo "No log files found"
          echo "Listing files in build directory (if exists)..."
          ls -la dist/ || echo "Build directory dist/ not found"

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}